[project]
name = "oban"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["alembic>=1.15.1", "psycopg>=3.2.5", "sqlalchemy>=2.0.38"]

[dependency-groups]
dev = ["pytest>=8.3.5", "ruff>=0.9.9"]
