[project]
name = "oban"
version = "0.1.0"
description = "Robust job processing, backed by modern PostgreSQL."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "psycopg>=3.2.5",
  "psycopg-pool>=3.2.6",
  "pydantic>=2.11.9",
]

[dependency-groups]
dev = ["pytest>=8.3.5", "ruff>=0.9.9"]

[tool.pytest.ini_options]
markers = [
    "oban: configure Oban instance options for a test",
]
